# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import graph

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DownloadGraph = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadGraph.setGeometry(QtCore.QRect(240, 60, 281, 51))
        self.DownloadGraph.setObjectName("DownloadGraph")
        self.ShowGraph = QtWidgets.QPushButton(self.centralwidget)
        self.ShowGraph.setGeometry(QtCore.QRect(240, 160, 281, 51))
        self.ShowGraph.setObjectName("ShowGraph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.AddFunction()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DownloadGraph.setText(_translate("MainWindow", "Загрузить граф"))
        self.ShowGraph.setText(_translate("MainWindow", "Вывести изображение"))

    def AddFunction(self):
        self.DownloadGraph.clicked.connect(lambda: self.UnpackGraph())
        
    def UnpackGraph(self): # Распаковка графа             
        NewGraph = graph.Graph()
        NewGraph.ShowGraph()
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
